#!/usr/bin/env python3
import argparse
import base64
import json
import os
import re
import tempfile
from pathlib import Path

from candidate_set_identity import expected_fingerprint

HEX40 = re.compile(r"^[0-9a-f]{40}$")
HEX64 = re.compile(r"^[0-9a-f]{64}$")
BUNDLE_ID = re.compile(r"^[A-Za-z0-9]+(?:[.-][A-Za-z0-9]+)+$")
ROLE = re.compile(r"^[A-Za-z][A-Za-z0-9]*$")
VERSION = re.compile(r"^[0-9]+(?:\.[0-9]+){1,2}$")


def fail(message: str) -> None:
    raise SystemExit(message)


def atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(handle, "wb") as destination:
            destination.write(data)
            destination.flush()
            os.fsync(destination.fileno())
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--role", required=True)
    parser.add_argument("--bundle-id", required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--build", required=True)
    parser.add_argument("--commit", required=True)
    parser.add_argument("--candidate-set-id", required=True)
    parser.add_argument("--swift-output", required=True)
    parser.add_argument("--c-output", required=True)
    parser.add_argument("--metadata-output", required=True)
    args = parser.parse_args()

    if not ROLE.fullmatch(args.role): fail("invalid artifact role")
    if not BUNDLE_ID.fullmatch(args.bundle_id): fail("invalid bundle identifier")
    if not VERSION.fullmatch(args.version): fail("invalid marketing version")
    if not args.build.isdigit() or int(args.build) < 1: fail("invalid build number")
    commit = args.commit.lower()
    if not HEX40.fullmatch(commit): fail("invalid full git commit")
    candidate_set_id = args.candidate_set_id.lower()
    if not HEX64.fullmatch(candidate_set_id): fail("invalid candidate set ID")

    normalized_build = str(int(args.build))
    fingerprint = expected_fingerprint(
        args.role,
        args.bundle_id,
        args.version,
        normalized_build,
        commit,
        candidate_set_id,
    )
    metadata = {
        "schemaVersion": 1,
        "role": args.role,
        "bundleIdentifier": args.bundle_id,
        "version": args.version,
        "build": normalized_build,
        "commit": commit,
        "visibleCommit": commit[:12],
        "fingerprint": fingerprint,
        "candidateSetID": candidate_set_id,
    }
    swift = f'''// Generated by scripts/generate-build-identity.py. Do not edit during CI.\nenum GeneratedBuildIdentity {{\n    static let version = "{args.version}"\n    static let build = "{int(args.build)}"\n    static let commit = "{commit[:12]}"\n    static let fingerprint = "{fingerprint}"\n    static let candidateSetID = "{candidate_set_id}"\n}}\n'''
    canonical_metadata = json.dumps(
        metadata, ensure_ascii=False, separators=(",", ":"), sort_keys=True
    ).encode("utf-8")
    encoded_marker = base64.urlsafe_b64encode(canonical_metadata).decode("ascii").rstrip("=")
    c_source = f'''/* Generated by scripts/generate-build-identity.py. Do not edit during CI. */
#if defined(__APPLE__)
__attribute__((used, section("__TEXT,__cjidentity")))
#else
__attribute__((used))
#endif
const char cangjie_build_identity_marker[] =
    "CANGJIE_IDENTITY_V1:{encoded_marker}";
'''
    atomic_write(Path(args.swift_output), swift.encode("utf-8"))
    atomic_write(Path(args.c_output), c_source.encode("utf-8"))
    atomic_write(
        Path(args.metadata_output),
        (json.dumps(metadata, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8"),
    )


if __name__ == "__main__":
    main()
